name: angular test and build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: './angular/'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './angular/package-lock.json'
    
    - name: install dependencies
      run: npm ci

    - name: run tests
      continue-on-error: true
      id: run_tests
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

    - name: send email on failure
      if: ${{ steps.run_tests.outcome == 'failure' }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.yandex.ru
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: running tests in ${{ github.job }} job of ${{ github.repository }} failed!
        to: ivanych5@yandex.ru
        from: Kirill Novichkov
        secure: true
        body: running tests in ${{ github.job }} job of ${{ github.repository }} failed!
      run: exit 1