name: angular test and build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: './angular/'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './angular/package-lock.json'
    
    - name: install dependencies
      run: npm ci

    - name: run tests
      continue-on-error: true
      id: run_tests
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

    - name: send email on failure
      run: |
        if [[ ${{ steps.run_tests.outcome }} == 'failure' ]]; 
        then exit 1;
        else exit 0;
        fi;