name: angular test and build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: './angular/'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './angular/package-lock.json'
    
    - name: install dependencies
      run: npm ci

    - name: run tests
      continue-on-error: true
      id: run_tests
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

    - name: send email on failure
      if: ${{ steps.run_tests.outcome == 'failure' }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.yandex.ru
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: running tests in ${{ github.job }} job of ${{ github.repository }} failed!
        to: ${{secrets.MAIL_USERNAME}}
        from: Kirill Novichkov
        secure: true
        body: running tests in ${{ github.job }} job of ${{ github.repository }} failed!
    
    - name: exit on failure
      if: ${{ steps.run_tests.outcome == 'failure' }}
      run: exit 1

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    needs: [test]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './angular/package-lock.json'
    
    - name: install dependencies
      run: npm ci

    - name: run build
      continue-on-error: true
      id: run_build
      run: npm run build

    - name: send email on failure
      if: ${{ steps.run_build.outcome == 'failure' }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.yandex.ru
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: running build in ${{ github.job }} job of ${{ github.repository }} failed!
        to: ${{secrets.MAIL_USERNAME}}
        from: Kirill Novichkov
        secure: true
        body: running build in ${{ github.job }} job of ${{ github.repository }} failed!
    
    - name: exit on failure
      if: ${{ steps.run_build.outcome == 'failure' }}
      run: exit 1

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}/angular-demo

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}